# =============================================================================
# Night-Shift — Multi-Provider LLM Client
# =============================================================================
# A unified interface for communicating with different LLM providers.
# The active provider is determined by the ``LLM_PROVIDER`` setting in
# the environment configuration:
#
#   "vllm"      → Local vLLM instance (OpenAI-compatible API)
#   "openai"    → OpenAI hosted API
#   "anthropic" → Anthropic Claude API
#
# All providers receive the same system prompt (the Night-Shift Data
# Extraction Agent prompt) and return a raw text response that the
# ``processor`` module will parse as JSON.
# =============================================================================

from __future__ import annotations

from app.core.config import Settings, get_settings
from app.core.logging import get_logger

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Night-Shift Agent System Prompt
# ---------------------------------------------------------------------------
# This prompt is defined in the project specification.  It instructs the
# LLM to act as a strict data cleaner and rule extractor, producing
# structured JSON output.
# ---------------------------------------------------------------------------
NIGHTSHIFT_SYSTEM_PROMPT = """
ROLE:
You are the Night-Shift Data Extraction Agent. You are an expert data engineer and analytical editor specializing in complex, domain-specific text (such as biotech and pharmaceutical licensing agreements, corporate contracts, and technical documentation).

OBJECTIVE:
Your job is to analyze the delta (the difference) between an initial AI-generated output and the final human-corrected output. From this delta, you must extract the underlying preference, rule, or stylistic choice the human was enforcing, and then generate a pristine, generalized training pair for future fine-tuning.

INPUT PROVIDED:
You will receive a raw log containing:
1. `system_prompt`: The original instructions given to the drafting AI.
2. `user_input`: The text or request the user provided.
3. `ai_output`: The rejected or suboptimal text generated by the AI.
4. `human_correction`: The final text after the human manually edited the AI's output.

INSTRUCTIONS:
1. **Analyze the Delta:** Compare the `ai_output` and the `human_correction`. Identify exactly what the human changed. Did they alter the formatting? Did they change the tone? Did they add a specific liability carve-out or modify a milestone payment structure?
2. **Extract the Core Rule:** Distill the human's edit into a single, highly specific, and actionable rule.
    * *Bad Rule:* "Make the contract better."
    * *Good Rule:* "Always capitalize 'Confidential Information' and ensure the indemnification clause explicitly excludes indirect damages."
3. **Clean and Sanitize:** Remove any highly specific, transient data from the prompt and response that wouldn't make sense in a generalized training dataset (e.g., removing a specific company's name if the rule is about general formatting).
4. **Generate the Training Pair:** Create a perfect `training_prompt` and `ideal_response` that inherently demonstrates the extracted rule without needing to be explicitly told the rule.

OUTPUT FORMAT:
You must output ONLY valid JSON matching the following schema. Do not include markdown formatting like ```json or any conversational text.

{
  "status": "processed",
  "extracted_rule": {
    "rule_summary": "A concise, actionable sentence describing the human's preference."
  },
  "fine_tuning_pair": {
    "training_prompt": "The sanitized user input/context.",
    "ideal_response": "The perfect AI response that incorporates the human's exact preference."
  }
}

Use "discarded" for the status ONLY if the human edit was just a typo fix or garbage data.
""".strip()


def _build_user_message(
    system_prompt: str,
    user_input: str,
    ai_output: str,
    human_correction: str,
) -> str:
    """
    Format the raw interaction log into the structured user message
    that the Night-Shift Agent expects.

    Parameters
    ----------
    system_prompt : str
        The original instructions given to the drafting AI.
    user_input : str
        The user request or uploaded source text.
    ai_output : str
        The AI-generated response (before edits).
    human_correction : str
        The final text after the user's manual edits.

    Returns
    -------
    str
        A formatted string ready to be sent as the user message.
    """
    return (
        f"system_prompt:\n{system_prompt}\n\n"
        f"user_input:\n{user_input}\n\n"
        f"ai_output:\n{ai_output}\n\n"
        f"human_correction:\n{human_correction}"
    )


# =============================================================================
# Provider-Specific Implementations
# =============================================================================


async def _call_vllm(settings: Settings, user_message: str) -> str:
    """
    Send a request to a local vLLM instance via its OpenAI-compatible API.

    vLLM exposes the same ``/v1/chat/completions`` endpoint as OpenAI,
    so we reuse the ``openai`` Python client with a custom ``base_url``.
    """
    from openai import AsyncOpenAI

    client = AsyncOpenAI(
        base_url=settings.vllm_base_url,
        api_key=settings.vllm_api_key,
    )

    logger.info(
        "llm_request_sending",
        provider="vllm",
        model=settings.vllm_model_name,
        base_url=settings.vllm_base_url,
    )

    response = await client.chat.completions.create(
        model=settings.vllm_model_name,
        messages=[
            {"role": "system", "content": NIGHTSHIFT_SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0.1,     # Low temperature for deterministic extraction
        max_tokens=4096,
    )

    return response.choices[0].message.content or ""


async def _call_openai(settings: Settings, user_message: str) -> str:
    """
    Send a request to the OpenAI hosted API.
    """
    from openai import AsyncOpenAI

    client = AsyncOpenAI(api_key=settings.openai_api_key)

    logger.info(
        "llm_request_sending",
        provider="openai",
        model=settings.openai_model_name,
    )

    response = await client.chat.completions.create(
        model=settings.openai_model_name,
        messages=[
            {"role": "system", "content": NIGHTSHIFT_SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0.1,
        max_tokens=4096,
    )

    return response.choices[0].message.content or ""


async def _call_anthropic(settings: Settings, user_message: str) -> str:
    """
    Send a request to the Anthropic Claude API.

    Anthropic uses a different message format — the system prompt is
    passed as a top-level parameter rather than as a message role.
    """
    from anthropic import AsyncAnthropic

    client = AsyncAnthropic(api_key=settings.anthropic_api_key)

    logger.info(
        "llm_request_sending",
        provider="anthropic",
        model=settings.anthropic_model_name,
    )

    response = await client.messages.create(
        model=settings.anthropic_model_name,
        system=NIGHTSHIFT_SYSTEM_PROMPT,
        messages=[
            {"role": "user", "content": user_message},
        ],
        temperature=0.1,
        max_tokens=4096,
    )

    # Anthropic returns content as a list of content blocks
    return response.content[0].text


# =============================================================================
# Public Interface
# =============================================================================

# Dispatch table mapping provider names to their handler functions
_PROVIDER_DISPATCH = {
    "vllm": _call_vllm,
    "openai": _call_openai,
    "anthropic": _call_anthropic,
}


async def analyse_interaction(
    system_prompt: str,
    user_input: str,
    ai_output: str,
    human_correction: str,
) -> str:
    """
    Send a raw interaction to the configured LLM provider for analysis.

    This is the main entry point used by the worker's ``agent.py``.
    It reads the active provider from the config, formats the user
    message, and dispatches to the appropriate handler.

    Parameters
    ----------
    system_prompt : str
        The original instructions given to the drafting AI.
    user_input : str
        The user request or uploaded source text.
    ai_output : str
        The AI-generated response (before edits).
    human_correction : str
        The final text after the user's manual edits.

    Returns
    -------
    str
        Raw text response from the LLM (expected to be valid JSON).

    Raises
    ------
    ValueError
        If the configured ``LLM_PROVIDER`` is not supported.
    """
    settings = get_settings()
    provider = settings.llm_provider

    handler = _PROVIDER_DISPATCH.get(provider)
    if handler is None:
        raise ValueError(
            f"Unsupported LLM provider: '{provider}'. "
            f"Supported: {list(_PROVIDER_DISPATCH.keys())}"
        )

    # Build the formatted user message from the raw interaction fields
    user_message = _build_user_message(
        system_prompt=system_prompt,
        user_input=user_input,
        ai_output=ai_output,
        human_correction=human_correction,
    )

    # Dispatch to the appropriate provider
    raw_response = await handler(settings, user_message)

    logger.info(
        "llm_response_received",
        provider=provider,
        response_length=len(raw_response),
    )

    return raw_response
